### ISSUE TITLE
Error on shift deletion

### ISSUE THREAD

**Issue by pitpalme** [coders4help/volunteer_planner#398]
When trying to delete a shift (no volunteers assigned to it) an error is raised.

```
  File "./scheduler/signals.py", line 38, in send_email_notifications
    reply_to = sender.email
AttributeError: type object 'Shift' has no attribute 'email'
```

Seems to have been introduced with 1694d90095b1a6076da992ff9e05674b06a291f2.

**Comment by pitpalme** [comment]
PR containing intermediate fix merged.
